global using EmployeeService.Enums;
global using EmployeeService.DTO_s;
global using EmployeeService.Repositories.Interfaces;
global using Microsoft.Data.SqlClient;
global using System.Data;
global using Dapper;
global using EmployeeService.Models;
global using static Dapper.SqlMapper;
global using EmployeeService.Repositories.Implementations;
global using EmployeeService.EndPoints;
global using System.Net;
global using System.Text.Json;
global using EmployeeService.Middlewares;
global using EmployeeService.Handlers.EmployeeHandler.Interfaces;
global using EmployeeService.Handlers.EmployeeHandler.Implementations;
global using EmployeeService.CustomExceptions;
global using System.ComponentModel.DataAnnotations;